name: watchtower
networks:
  main:
    external: true
services:
  watchtower:
    command:
      - portainer
      - nginxproxymanager
      - pufferpanel
      - playit-agent
      - ollama-cpu
      - open-webui
      - flaresolverr
      - jellyfin
      - prowlarr
      - qbittorrent
      - radarr
      - sonarr
      - prometheus
      - grafana
      - cadvisor
      - node_exporter
    container_name: watchtower
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NOTIFICATION_URL: telegram://${TELEGRAM_BOT_TOKEN}@telegram/?channels=${TELEGRAM_CHAT_ID}
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_SCHEDULE: 0 0 * * *
    image: containrrr/watchtower:latest
    networks:
      main: null
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
