version: "3.8"

services:
  web:
    image: php:8.2-apache
    container_name: xampp_web
    ports:
      - "8080:80"
    volumes:
      - ./web_data:/var/www/html
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - xampp_net

  db:
    image: mysql:latest
    container_name: xampp_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - xampp_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: xampp_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - xampp_net
