name: media
services:
  flaresolverr:
    container_name: flaresolverr
    environment:
      CAPTCHA_SOLVER: none
      LOG_HTML: "false"
      LOG_LEVEL: info
      TZ: Europe/London
    image: ghcr.io/flaresolverr/flaresolverr:latest
    networks:
      main: null
    ports:
      - 8191:8191
    restart: unless-stopped

  jellyfin:
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    image: jellyfin/jellyfin:latest
    networks:
      main: null
    ports:
      - 8096:8096
    restart: unless-stopped
    volumes:
      - /DATA/AppData/jellyfin:/config
      - /mnt/Storage2/media/library/movies:/movies
      - /mnt/Storage2/media/library/shows:/shows

  prowlarr:
    container_name: prowlarr
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    image: lscr.io/linuxserver/prowlarr:latest
    networks:
      main: null
    ports:
      - 9696:9696
    restart: unless-stopped
    volumes:
      - /DATA/AppData/prowlarr:/config

  qbittorrent:
    container_name: qbittorrent
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
      WEBUI_PORT: "8082"
    image: lscr.io/linuxserver/qbittorrent:latest
    networks:
      main: null
    ports:
      - 8082:8082
      - 6881:6881
    restart: unless-stopped
    volumes:
      - /DATA/AppData/qbittorrent:/config
      - /mnt/Storage2/media/torrent:/downloads

  radarr:
    container_name: radarr
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    image: lscr.io/linuxserver/radarr:latest
    networks:
      main: null
    ports:
      - 7878:7878
    restart: unless-stopped
    volumes:
      - /DATA/AppData/radarr:/config
      - /mnt/Storage2/media/library/movies:/movies
      - /mnt/Storage2/media/torrent/movies:/downloads

  sonarr:
    container_name: sonarr
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    image: lscr.io/linuxserver/sonarr:latest
    networks:
      main: null
    ports:
      - 8989:8989
    restart: unless-stopped
    volumes:
      - /DATA/AppData/sonarr:/config
      - /mnt/Storage2/media/library/shows:/shows
      - /mnt/Storage2/media/torrent/shows:/downloads
networks:
  main:
    external: true
