version: "3.8"
networks:
  main:
    external: true

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    networks:
      - main
    volumes:
      - /DATA/AppData/ollama/.ollama:/root/.ollama
      - /mnt/Storage2/ai/models:/root/.ollama/models
    ports:
      - 11434:11434
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    networks:
      - main
    volumes:
      - /DATA/AppData/ollama/.ollama:/root/.ollama
      - /DATA/AppData/open-webui:/app/backend/data
    ports:
      - 8081:8080
